Work around AttributeError: 'module' object has no attribute 'Sequencer'
I'm getting that error on Python 3 and I don't quite understand how the
sequencer module works here (src/sequencer.py doesn't define a Sequencer
class!).